# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c20c4649112c6dacf04ec1e944e021d"
name = "omni-ai-suite"
handle = "omni-ai-suite"
application_url = "https://omni-ai-suite.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,read_orders,write_marketing_events"

[auth]
redirect_urls = ["https://omni-ai-suite.vercel.app/auth/callback", "https://omni-ai-suite.vercel.app/auth/shopify/callback", "https://omni-ai-suite.vercel.app/api/auth/callback"]

[pos]
embedded = false
